services:
    # Production service
    corporate-site:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - PORT=3000
        restart: unless-stopped
        container_name: corporate-site

    # Development service
    corporate-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3001:3000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        container_name: corporate-dev
        stdin_open: true
        tty: true
